fix: converter renaming already named tensors
pytorch/TensorRT pull request #1167
Opened 2022-07-06 19:21 UTC by bowang007

Signed-off-by: Bo Wang <bowa@nvidia.com>

# Description

It happens that some ITensors are renamed in conversion process, which might cause binding issues. 
We should at least give a warning message when this happens. 
Also, we should go through converter library to ensure that ITensor names are not changed. 

Fixes #1004 
A PR to fix this issue for aten::to converter: #1108

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [ ] My code follows the style guidelines of this project (You can use the linters)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added the relevant labels to my PR in so that relevant reviewers are notified

2022-07-06 22:08 UTC, narendasan commented
@bowang007 Have you noticed any new warnings as a result of this patch?

2022-07-10 23:36 UTC, narendasan requested changes

2022-07-11 17:40 UTC, bowang007 commented
> @bowang007 Have you noticed any new warnings as a result of this patch?

yes, I tested this patch with several different examples that incurs this error #1004  we have locally, there are new warnings.

2022-07-21 04:00 UTC, peri044 requested changes

2022-07-21 04:02 UTC, peri044 commented on core/conversion/conversionctx/ConversionCtx.cpp
> +bool ConversionCtx::AddNamedTensor(const torch::jit::Value* value, nvinfer1::ITensor* tensor) {
How about just RecordITensor() ?. It will record or else warn if the ITensor is new.

2022-07-21 04:04 UTC, peri044 commented
Functionality LGTM. Just finalizing names is left to merge.

2022-07-23 11:51 UTC, merged