fix: Properly cast Int8 inputs to TensorRT Engines in Fallback
pytorch/TensorRT pull request #1549
Opened 2022-12-14 04:58 UTC by gs-olive

# Description
- Fix compilation error for GPT-2 model arising from Byte-type inputs fed into TensorRT Engine
- Update translation dictionary between Torch and TensorRT types to include `at::kByte`
- Add field to PartitioningInfo specifying whether to cast Int8 inputs to TensorRT Engines to Int, to avoid error arising from Int8 inputs being fed into non-quantized engines
- Add automatic detection of quantized/calibrated models and disable Int8 => Int32 casting in those cases
- Fix bug where LoweringInfo target device was not being updated for Python API
- Allow `castNode` to force creation of a new node and avoid searching for an existing one to convert
- Add test to ensure cast is inserted in the Torch engine preceding a TensorRT engine, when the Byte tensor is an output of the Torch engine

Error displayed when passing `Int8` inputs to non-quantized TRT Engine:

```python
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: input_0: input/output with DataType Int8 in network without Q/DQ layers must have dynamic range set when no calibrator is used.
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 4: [network.cpp::validate::2772] Error Code 4: Internal Error (DataType does not match TensorFormats.)
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 2: [builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
```

With this PR, GPT-2 now compiles and runs inference successfully.

Fixes #1455 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

# Checklist:

- [ x ] My code follows the style guidelines of this project (You can use the linters)
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ x ] I have made corresponding changes to the documentation
- [ x ] I have added tests to verify my fix or my feature
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] I have added the relevant labels to my PR in so that relevant reviewers are notified

2022-12-20 01:23 UTC, gs-olive commented on core/partitioning/partitioninginfo/PartitioningInfo.h
> +  bool cast_int8 = false;
Yes, I can make this change - though the casting does not apply to user-provided inputs, it only applies to internal tensors generated during/for computation

2022-12-22 00:31 UTC, peri044 commented on core/partitioning/shape_analysis.cpp
> +          seg_block.g()->block()->replaceOutput(i, cast_node->outputs()[0]);
Can we add LOG_DEBUG statements to ensure we log all the casting and user understands the flow by the logs ?

2022-12-22 01:36 UTC, peri044 requested changes

2022-12-22 01:36 UTC, peri044 commented on core/partitioning/shape_analysis.cpp
>        }
We internally discussed adding a cast node for t ==at::kByte as well. Also making dtype a parameter for `createCastNode` call

2022-12-22 02:27 UTC, gs-olive commented on core/partitioning/shape_analysis.cpp
>        }
I manually made the formatting changes to reduce redundancy of `if` statements, but they should be functionally equivalent to the previous version

2022-12-22 07:26 UTC, peri044 approved these changes
LGTM

2022-12-22 07:26 UTC, merged