Lowering aten::pad to aten::constant_pad_nd/aten::reflection_padXd/aten::replication_padXd
pytorch/TensorRT pull request #1588
Opened 2023-01-12 03:53 UTC by ruoqianguo

# Description

Lowering aten::pad to aten::constant_pad_nd/aten::reflection_padXd/aten::replication_padXd

Fixes #1566 

## Type of change

Please delete options that are not relevant and/or add your own.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [x] I have made corresponding changes to the documentation
- [x] I have added tests to verify my fix or my feature
- [x] New and existing unit tests pass locally with my changes
- [x] I have added the relevant labels to my PR in so that relevant reviewers are notified

2023-01-20 00:31 UTC, narendasan reviewed
Please run the pre-commit tasks

2023-01-30 07:09 UTC, ruoqianguo commented
Hi @narendasan , I have run the pre-commit tasks.

2023-01-31 02:09 UTC, narendasan requested changes
Changes seem fine, just make sure to add the new file to the CMake build system as well

2023-01-31 04:44 UTC, ruoqianguo commented
> Changes seem fine, just make sure to add the new file to the CMake build system as well

Hi @narendasan , I have added the new file to the CMake system. All checks have passed.

2023-02-03 00:45 UTC, peri044 commented
Expected this PR to make into 23.03 NGC release

2023-02-06 23:00 UTC, merged