feat: add a pre-AOT lowering pass to remove detach ops
pytorch/TensorRT pull request #2756
Opened 2024-04-16 22:30 UTC by zewenli98

# Description

Added a pre-AOT lowering pass to remove `detach` ops

Fixes #2657 

## Type of change

- New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project (You can use the linters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas and hacks
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to verify my fix or my feature
- [ ] New and existing unit tests pass locally with my changes
- [x] I have added the relevant labels to my PR in so that relevant reviewers are notified

2024-04-17 00:38 UTC, gs-olive reviewed
Looks good - if possible, could a model with an explicit `detach()` call be added as a test case?

2024-04-17 01:22 UTC, apbose commented
Overall looks good to me. Is there any use case for which this lowering pass has been added?

2024-04-17 16:58 UTC, peri044 requested changes
I've implemented your fix (refactored it a bit) as a part of https://github.com/pytorch/TensorRT/pull/2756/files. Can you take a look make these changes? 
We need to add this pass to both torch.compile and torch.export as well.

2024-04-17 22:03 UTC, zewenli98 commented
> Overall looks good to me. Is there any use case for which this lowering pass has been added?

Yes, in the vLLM, without this lowering pass, it causes some errors during compilation.

2024-04-19 06:46 UTC, zewenli98 commented
> I've implemented your fix (refactored it a bit) as a part of https://github.com/pytorch/TensorRT/pull/2756/files. Can you take a look and make these changes? We need to add this pass to both torch.compile and torch.export as well.

Where can I find your implementation? The link seems not including your change.

2024-04-22 23:14 UTC, peri044 commented
> > I've implemented your fix (refactored it a bit) as a part of https://github.com/pytorch/TensorRT/pull/2756/files. Can you take a look and make these changes? We need to add this pass to both torch.compile and torch.export as well.
> 
> Where can I find your implementation? The link seems not including your change.

My bad, here's the correct link : https://github.com/pytorch/TensorRT/pull/2763

2024-04-25 00:12 UTC, zewenli98 commented
Hi @peri044 I checked your PR and found you made a lot of changes like `pre_export_lowering` and `post_lowering` with the help of PassManager. I will rebase on your PR after it gets merged.

Besides, I noticed that [`_pretraced_backend()`](https://github.com/pytorch/TensorRT/blob/dad53993243aeb0dca5c5477b6bdc936933c3a39/py/torch_tensorrt/dynamo/backend/backends.py#L54) in `backends.py` and [`compile()`](https://github.com/pytorch/TensorRT/blob/dad53993243aeb0dca5c5477b6bdc936933c3a39/py/torch_tensorrt/dynamo/_compiler.py#L47) in `_compiler.py` are pretty similar. Why do we need the separate functions?

2024-05-17 17:33 UTC, peri044 commented
> Hi @peri044 I checked your PR and found you made a lot of changes like `pre_export_lowering` and `post_lowering` with the help of PassManager. I will rebase on your PR after it gets merged.
> 
> Besides, I noticed that [`_pretraced_backend()`](https://github.com/pytorch/TensorRT/blob/dad53993243aeb0dca5c5477b6bdc936933c3a39/py/torch_tensorrt/dynamo/backend/backends.py#L54) in `backends.py` and [`compile()`](https://github.com/pytorch/TensorRT/blob/dad53993243aeb0dca5c5477b6bdc936933c3a39/py/torch_tensorrt/dynamo/_compiler.py#L47) in `_compiler.py` are pretty similar. Why do we need the separate functions?

We use the same function now https://github.com/pytorch/TensorRT/pull/2763. Closing this PR now

2024-05-21 23:42 UTC, closed without merging