full_like evaluator
pytorch/TensorRT pull request #2917
Opened 2024-06-13 19:33 UTC by apbose

2024-06-13 23:19 UTC, peri044 requested changes

2024-06-13 23:19 UTC, peri044 commented on py/torch_tensorrt/dynamo/conversion/ops_evaluators.py
> +from torch_tensorrt.fx.utils import Frameworks, unified_dtype_converter
We have our own types and switch from `unified_dtype_converter` to using `_enums.dtype.to` and `_enums.dtype.from` for type conversions. We shouldn't be using FX utils anymore.

2024-06-13 23:19 UTC, peri044 commented on py/torch_tensorrt/dynamo/conversion/ops_evaluators.py
> +        full_like_np_tensor = np.full(
Can you also add dynamic shape support ? what if the input shape has -1 in it ? Please refer to fill layer which can help you out here.

2024-08-06 19:49 UTC, peri044 commented
@apbose  what is the status of full_like ?

2024-08-06 20:27 UTC, apbose commented
I did not work on this since long. I should be able to take a look at this next week when I am done with dynamic shape of aten::chunk and aten::tile and merge the remaining PRs.

2024-08-22 16:40 UTC, peri044 commented
Closing this as we now have a lowering pass that handles this.

2024-08-22 16:40 UTC, closed without merging